import React from 'react';
import { Check, Copy, Info, Router, Smartphone, Users, Wifi, X } from 'lucide-react';
import InternetSharing, { SharingStatus } from '../utils/internetSharingBridge';

interface Props { isOpen: boolean; onClose: () => void; }
const empty: SharingStatus = { active: false, supported: true, ssid: 'OODI-NETSHARE', proxyHost: '192.168.49.1', proxyPort: 8282, devices: [], downloadBytes: 0, uploadBytes: 0 };
const bytes = (n: number) => n < 1024 * 1024 ? `${(n / 1024).toFixed(1)} KB` : `${(n / 1048576).toFixed(2)} MB`;

export const NetShareModal: React.FC<Props> = ({ isOpen, onClose }) => {
  const [status, setStatus] = React.useState(empty); const [ssid, setSsid] = React.useState('OODI-NETSHARE'); const [password, setPassword] = React.useState('oodi12345'); const [band, setBand] = React.useState<'auto' | '2ghz' | '5ghz'>('auto'); const [ipv6, setIpv6] = React.useState(true); const [busy, setBusy] = React.useState(false); const [copied, setCopied] = React.useState(false); const [message, setMessage] = React.useState('');
  React.useEffect(() => { if (!isOpen) return; let cancelled = false; const refresh = () => { void InternetSharing.getStatus().then(next => { if (!cancelled) setStatus(next); }).catch(() => undefined); }; refresh(); const timer = window.setInterval(refresh, 1500); return () => { cancelled = true; window.clearInterval(timer); }; }, [isOpen]);
  if (!isOpen) return null;
  const toggle = async () => { setBusy(true); setMessage(''); try { const next = status.active ? await InternetSharing.stop() : await InternetSharing.start({ ssid, password, band, ipv6, proxyHost: '192.168.49.1', proxyPort: 8282, shareVpn: true }); setStatus(next); if (next.message && !next.active) setMessage(next.message); } catch (e) { setMessage(e instanceof Error ? e.message : 'تعذر تشغيل البث'); } finally { setBusy(false); } };
  const copy = async () => { await navigator.clipboard?.writeText(`${status.proxyHost}:${status.proxyPort}`); setCopied(true); setTimeout(() => setCopied(false), 1000); };
  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/85 p-3 backdrop-blur-md"><div className="w-full max-w-lg max-h-[94vh] overflow-y-auto rounded-[28px] border border-cyan-500/30 bg-[#080d24] p-5 text-right shadow-2xl" dir="rtl">
    <div className="flex items-center justify-between border-b border-slate-800 pb-4"><button onClick={onClose} className="rounded-xl bg-slate-800 p-2 text-slate-300"><X className="h-5 w-5" /></button><div className="flex items-center gap-3"><div><h2 className="text-lg font-black text-white">مشاركة الإنترنت</h2><p className="text-[11px] text-cyan-300">NetShare — إعدادات كاملة</p></div><Wifi className="h-7 w-7 text-cyan-300" /></div></div>
    <div className={`mt-4 rounded-2xl border p-4 ${status.active ? 'border-emerald-400/40 bg-emerald-400/10' : 'border-slate-700 bg-slate-900/70'}`}><div className="flex items-center justify-between gap-3"><button disabled={busy} onClick={toggle} className={`rounded-xl px-4 py-2 text-xs font-black ${status.active ? 'bg-rose-500/20 text-rose-200' : 'bg-gradient-to-r from-cyan-500 to-blue-600 text-white'} disabled:opacity-50`}>{busy ? 'جارٍ…' : status.active ? 'إيقاف المشاركة' : 'بدء بث الإنترنت'}</button><div className="flex items-center gap-2"><div><div className="text-sm font-black text-white">{status.active ? 'المشاركة تعمل' : 'المشاركة متوقفة'}</div><div className="text-[10px] text-slate-400">NetShare مستقل عن خادم WireGuard وإعدادات التوجيه في التطبيق</div></div><span className={`h-3 w-3 rounded-full ${status.active ? 'bg-emerald-400' : 'bg-slate-600'}`} /></div></div></div>
    <div className="mt-3 grid grid-cols-2 gap-3"><label className="rounded-2xl border border-slate-700 bg-slate-900/70 p-3"><span className="text-[11px] text-slate-400">اسم الشبكة</span><input value={ssid} onChange={e => setSsid(e.target.value)} className="mt-2 w-full bg-transparent text-sm font-bold text-white outline-none" /></label><label className="rounded-2xl border border-slate-700 bg-slate-900/70 p-3"><span className="text-[11px] text-slate-400">كلمة المرور</span><span className="mt-1 block text-[9px] text-amber-300">يجب أن تكون من 8 أحرف أو أرقام على الأقل</span><input minLength={8} value={password} onChange={e => setPassword(e.target.value)} className="mt-1 w-full bg-transparent text-sm font-bold text-white outline-none" /></label></div>
    <div className="mt-3 rounded-2xl border border-slate-700 bg-slate-900/70 p-3"><div className="mb-2 flex items-center justify-between"><span className="text-[11px] text-slate-400">تردد الشبكة</span><span className="text-[10px] text-cyan-300">Wi‑Fi Direct band</span></div><div className="grid grid-cols-3 gap-2">{([['auto', 'تلقائي'], ['2ghz', '2.4 GHz'], ['5ghz', '5 GHz']] as const).map(([value, label]) => <button key={value} type="button" onClick={() => setBand(value)} className={`rounded-xl border px-2 py-2 text-xs font-bold transition ${band === value ? 'border-cyan-400 bg-cyan-500/20 text-cyan-100' : 'border-slate-700 bg-slate-950/40 text-slate-400 hover:border-slate-500'}`}>{label}</button>)}</div></div>
    <button type="button" onClick={() => setIpv6(value => !value)} className={`mt-3 flex w-full items-center justify-between rounded-2xl border p-3 text-right transition ${ipv6 ? 'border-cyan-400/40 bg-cyan-500/10' : 'border-slate-700 bg-slate-900/70'}`} dir="rtl"><span><span className="block text-xs font-bold text-white">IPv6 / الجيل السادس</span><span className="mt-1 block text-[10px] text-slate-400">السماح باتصالات IPv6 داخل NetShare</span></span><span className={`relative h-6 w-11 rounded-full transition ${ipv6 ? 'bg-cyan-500' : 'bg-slate-700'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${ipv6 ? 'right-1' : 'right-6'}`} /></span></button>
    <div className="mt-3 rounded-2xl border border-cyan-500/25 bg-cyan-500/10 p-4"><div className="flex items-center justify-between"><button onClick={copy} className="flex items-center gap-1 rounded-lg bg-slate-950/50 px-2 py-1 text-[10px] text-cyan-200">{copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}{copied ? 'تم النسخ' : 'نسخ'}</button><div className="flex items-center gap-2 text-xs font-bold text-cyan-100"><span>Proxy للأجهزة المتصلة</span><Router className="h-4 w-4" /></div></div><div className="mt-3 grid grid-cols-2 gap-2 font-mono text-xs"><div className="rounded-xl bg-slate-950/50 p-2 text-center text-cyan-300">{status.proxyHost}</div><div className="rounded-xl bg-slate-950/50 p-2 text-center text-cyan-300">{status.proxyPort}</div></div></div>
    <div className="mt-3 grid grid-cols-3 gap-2"><div className="rounded-xl border border-slate-800 bg-slate-900/60 p-3 text-center"><Users className="mx-auto h-4 w-4 text-cyan-300" /><b className="mt-1 block text-white">{status.devices.length}</b><span className="text-[10px] text-slate-500">الأجهزة</span></div><div className="rounded-xl border border-slate-800 bg-slate-900/60 p-3 text-center"><b className="block text-emerald-300">↓ {bytes(status.downloadBytes)}</b><span className="text-[10px] text-slate-500">تحميل</span></div><div className="rounded-xl border border-slate-800 bg-slate-900/60 p-3 text-center"><b className="block text-fuchsia-300">↑ {bytes(status.uploadBytes)}</b><span className="text-[10px] text-slate-500">رفع</span></div></div>
    {status.devices.map(d => <div key={d.id} className="mt-2 rounded-xl border border-slate-800 bg-slate-900/60 p-3"><div className="flex items-center justify-between"><span className="font-mono text-[10px] text-slate-500">{d.address}</span><span className="flex items-center gap-2 text-xs font-bold text-white"><span>{d.name}</span><Smartphone className="h-4 w-4 text-cyan-300" /></span></div><div className="mt-2 flex justify-between text-[10px] text-slate-400"><span className="text-emerald-300">↓ {bytes(d.downloadBytes ?? 0)}</span><span className="text-fuchsia-300">↑ {bytes(d.uploadBytes ?? 0)}</span><span>المجموع {bytes(d.bytes)}</span></div></div>)}
    {(message || !status.supported) && <div className="mt-3 flex items-start gap-2 rounded-xl border border-amber-500/25 bg-amber-500/10 p-3 text-[11px] text-amber-100"><Info className="h-4 w-4 shrink-0" /><span>{message || 'هذا الجهاز لا يدعم تشغيل Hotspot من التطبيق.'}</span></div>}
    <div className="mt-3 flex items-start gap-2 rounded-xl border border-blue-500/20 bg-blue-500/10 p-3 text-[10px] leading-relaxed text-blue-100"><Info className="h-4 w-4 shrink-0" /><span>هذه شبكة Wi‑Fi Direct افتراضية من نوع NetShare وليست Hotspot الهاتف. بعد بث الشبكة والاتصال بالهاتف المستلم للإنترنت، اذهب إلى إعدادات شبكة Wi‑Fi، واجعل الخادم الوكيل يدويًا، ثم أضف الخادم الوكيل 192.168.49.1 والبورت 8282. للتطبيقات التي تدعم SOCKS5 استخدم المنفذ 8181، وإعدادات Hotspot الموجودة في القائمة لا تتأثر.</span></div>
  </div></div>;
};
